BEGIN 
 INSERT INTO IPHONE VALUES ('&MODEL',&PRICE);
  COMMIT;
   DBMS_OUTPUT.PUT_LINE('RECORD INSERTED SUCESSFULLY');
    EXCEPTION 
	WHEN DUP_VAL_ON_INDEX THEN 
	 DBMS_OUTPUT.PUT_LINE('DUPLICATED RECORD ,TRY UNIQUE RECORD');
	  WHEN OTHERS THEN 
	  DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG,TRY AFTER WHILE');
	  
	  
	 END;
	 /